name = "MirrorVI"
uuid = "43bd0308-48b6-4215-9a59-ff2b06d2c4bd"
authors = ["Marco Molinari <marco.molinari@medisin.uio.no>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
